Test first within temporary directory, add rollback, add cleanup, add copy successful version

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -11,8 +11,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # - name: Checkout code
-      #   uses: actions/checkout@v4
       - name: Get repo name
         run: |
           echo "REPO_NAME=$(basename ${{github.repository}})" >> $GITHUB_ENV
@@ -24,14 +22,58 @@ jobs:
         run: |
           echo  "${VPS_KEY}" > private.key && chmod 600 private.key;
           ssh -i private.key -o StrictHostKeyChecking=no "${VPS_USER}"@"${VPS_HOST}" <<END
-            rm -rf "$REPO_NAME";
+            echo "Making temporary directory...";
+            TEMP_DIR=$(mktemp);
+            cd "$TEMP_DIR";
+            echo "Entered temporary directory: $TEMP_DIR";
             git clone --branch ${{github.ref_name}} --depth 1 "${{github.server_url}}/${{github.repository}}.git";
             cd "$REPO_NAME";
             git checkout "${{github.ref_name}}";
+            cp ~/env/${REPO_NAME}/.env .env;
+            echo "Copied envars"
+            
+
+            echo "Rebuilding images...";
+            sudo docker-compose --env-file .env -f docker/docker-compose-prod.yml build;
+
+            if [ $? -ne 0 ]; then
+              echo "Build failed, exiting.";
+              exit 1;
+            fi
+
             echo "Dropping old containers ...";
-            sudo docker-compose -f docker/docker-compose-prod.yml down gotravix-api db-migrator --remove-orphans;
-            echo "Rebuilding and deploying containers ...";
-            sudo docker-compose --env-file ../env/${REPO_NAME}/.env -f docker/docker-compose-prod.yml up -d --build gotravix-api;
+            sudo docker-compose -f docker/docker-compose-prod.yml down --remove-orphans gotravix-api db-migrator;
+
+            if [ $? -ne 0 ]; then
+              echo "Failed to stop old containers, exiting.";
+              exit 1;
+            fi
+
+            echo "Deploying new containers ...";
+            sudo docker-compose --env-file .env -f docker/docker-compose-prod.yml up -d gotravix-api db-migrator;
+
+            if [ $? -ne 0 ]; then
+              echo "Deployment failed, rolling back!";
+              sudo docker-compose -f docker/docker-compose-prod.yml down --remove-orphans gotravix-api db-migrator;
+              cd ~/"${REPO_NAME}";
+              sudo docker-compose --env-file .env -f docker/docker-compose-prod.yml up -d gotravix-api db-migrator;
+              if [ $? -ne 0 ]; then
+                echo "Rollback failed, Admistrator needs to fix the issue!";
+                echo "Exiting"
+                exit 1;
+              fi
+              echo "Rollback successful!";
+              echo "Exiting"
+              exit 1;
+            fi
+
+            echo "Successfully deployed ${REPO_NAME} on branch ${{github.ref_name}}";
+            cp -rf . ~/"${REPO_NAME}";
+            echo "Moved new repo to home directory";
+            cd ~/"${REPO_NAME}";
+            echo "Cleaning up temporary directory...";
+            rm -rf "$TEMP_DIR";
+            echo "Done!";
           END
 
 
